# Prometheus configuration for Environment Configuration Manager

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: "env-config-manager"

# Alertmanager configuration (optional)
# alerting:
#   alertmanagers:
#     - static_configs:
#         - targets:
#           - 'alertmanager:9093'

# Load rules once and periodically evaluate them
# rule_files:
#   - "alerts.yml"

# Scrape configurations
scrape_configs:
  # Environment Configuration Manager API
  - job_name: "env-config-manager"
    static_configs:
      - targets: ["localhost:3000"]
    metrics_path: "/metrics"
    scrape_interval: 15s
    scrape_timeout: 10s

  # Prometheus itself
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
