{{- if .Values.frontend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "env-config-manager.fullname" . }}-frontend
  labels:
    {{- include "env-config-manager.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
  - port: {{ .Values.frontend.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    {{- include "env-config-manager.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
{{- end }}
