{{- if .Values.worker.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "env-config-manager.fullname" . }}-worker
  labels:
    {{- include "env-config-manager.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  {{- if not .Values.worker.autoscaling.enabled }}
  replicas: {{ .Values.worker.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "env-config-manager.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: worker
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
      labels:
        {{- include "env-config-manager.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: worker
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "env-config-manager.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: worker
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        image: "{{ .Values.image.registry }}/{{ .Values.worker.image.repository }}:{{ .Values.worker.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: DATABASE_URL
          value: {{ include "env-config-manager.mongodbUrl" . | quote }}
        - name: REDIS_URL
          value: {{ include "env-config-manager.redisUrl" . | quote }}
        {{- if not .Values.mongodb.external.enabled }}
        - name: MONGO_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "env-config-manager.fullname" . }}-secrets
              key: MONGO_ROOT_PASSWORD
        {{- end }}
        {{- if not .Values.redis.external.enabled }}
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "env-config-manager.fullname" . }}-secrets
              key: REDIS_PASSWORD
        {{- end }}
        envFrom:
        {{- toYaml .Values.worker.envFrom | nindent 10 }}
        resources:
          {{- toYaml .Values.worker.resources | nindent 10 }}
{{- end }}
